review: 3주차 작업 멘토님 리뷰
kakao-tech-campus-2nd-step3/Team21_BE pull request #17
Opened 2024-09-20 14:08 UTC by peeerr

## 🔗 관련 이슈
#1 #3 #6 #7 #10 #13 

## 💬 리뷰
중점적으로 리뷰 받고 싶은 부분, 질문 등은 리드미에 작성해두었습니다!

2024-09-22 09:36 UTC, khj68 requested changes
고생하셨습니다!
의견드린 개선사항들 취사 선택하여 수정해보시길 추천드립니다.

2024-09-22 09:36 UTC, khj68 commented on src/main/java/com/potatocake/everymoment/config/SecurityConfig.java
> +                .addFilterAt(new LoginFilter(filterProcessesUrl, objectMapper, jwtUtil, memberRepository,
JwtFilter와 LoginFilter도 SecurityConfig 내에서 Bean 으로 등록하여 사용하는 것이 유지보수 및 가독성 측면에서 좋아보입니다 :)

2024-09-22 09:36 UTC, khj68 commented on src/main/java/com/potatocake/everymoment/controller/DiaryController.java
> +    @GetMapping("my")
/my 가 되어야 할 듯 해요 :)

2024-09-22 09:36 UTC, khj68 commented on src/main/java/com/potatocake/everymoment/controller/DiaryController.java
> +        return ResponseEntity.ok(response);
전반적으로 controller response 생성 시 보일러플레이트 코드가 반복되는 것으로 보이는데요!
이 부분을 어떻게 해결할 수 있을지 고민해보시면 좋을 것 같습니다 :)

2024-09-22 09:36 UTC, khj68 commented on src/main/java/com/potatocake/everymoment/controller/DiaryController.java
> +@RequestMapping("api/diaries")
/api/diaries 가 좋을 듯 합니다 :)

2024-09-22 09:36 UTC, khj68 commented on src/main/java/com/potatocake/everymoment/controller/DiaryController.java
> +public class DiaryController {
전반적으로 하나의 컨트롤러 클래스에서 너무 많은 역할을 수행하고 있는 것으로 보입니다.
일기 생성/수정/삭제
나머지 토글, 공개 설정
과 같이 클래스를 분리하는 것도 고려해보면 좋을 것 같아요 :)

2024-09-22 09:36 UTC, khj68 commented on src/main/java/com/potatocake/everymoment/dto/LocationPoint.java
> +    }
이걸 실제로 활용하는 비즈니스 로직이 있을까요?

2024-09-22 09:36 UTC, khj68 commented on src/main/java/com/potatocake/everymoment/dto/request/DiaryAutoRequest.java
> +public class DiaryAutoRequest {
네이밍이 명확하지 않은 것 같습니다. Auto로 "생성" 한다는 명확한 행위에 대한 동사가 추가적으로 필요해보입니다 :)
AutoCreateDiaryRequest와 같이요.

2024-09-22 09:36 UTC, khj68 commented on src/main/java/com/potatocake/everymoment/entity/Diary.java
> +    private String locationPoint;  // Java에서는 문자열로 처리
위경도를 string으로 처리하는 이유가 있을까요?

2024-09-22 09:36 UTC, khj68 commented on src/main/java/com/potatocake/everymoment/exception/ErrorCode.java
> +public enum ErrorCode {
에러코드를 분리해둔 것 좋습니다.
다만 도메인이 복잡해지고 서비스가 커질 수록 모든 에러를 하나의 파일에서 관리하는 것은 좋지 않은 방향입니다.
도메인 별로, 나아가서는 useCase 별로 클래스가 분리될 수 있도록 고려해주세요 :)

2024-09-22 09:36 UTC, khj68 commented on src/main/java/com/potatocake/everymoment/service/DiaryService.java
> +    }
이런 부분은 @RequiredArgsConstructor로 변경해두어도 좋을 것 같아요 :)

2024-09-22 09:36 UTC, khj68 commented on src/main/java/com/potatocake/everymoment/service/DiaryService.java
> +        String content = "현재 " + savedDiary.getLocationName() + "에 머무르고 있어요! 지금 기분은 어떠신가요?";
문자열은 최대한 constant로 관리가 되면 좋을 것 같아요 :)

2024-09-22 09:36 UTC, khj68 commented on src/main/java/com/potatocake/everymoment/service/DiaryService.java
> +                .type("MOOD_CHECK")
이런 타입과 같은 부분은 문자열보다 enum으로 관리가 되면 좋을 것 같습니다 :)

2024-09-22 09:36 UTC, khj68 commented on src/main/java/com/potatocake/everymoment/service/DiaryService.java
> +                .locationPoint(diaryManualRequest.getLocationPoint().toString())
위경도를 문자열로 저장하기 위해서 toString을 계속 적용해주어야 하는데요. 이런 부분이 유지보수를 힘들게 하는 원인 중 하나입니다!

converter를 적용하거나 위경도를 그대로 적용하는 것이 어떤가 하는 의견 드려봅니다 :)

2024-09-22 09:36 UTC, khj68 commented on src/main/java/com/potatocake/everymoment/service/DiaryService.java
> +        }
```
Specification<Diary> spec = Specification.where(DiarySpecification.filterDiaries(keyword, emoji, date, from, until, isBookmark))
    .and((root, query, builder) -> builder.equal(root.get("memberId"), memberId));

if (category != null) {
    spec = spec.and((root, query, builder) -> {
        Join<Diary, DiaryCategory> join = root.join("diaryCategories");
        return builder.equal(join.get("categoryId"), category);
    });
}

diaryPage = diaryRepository.findAll(spec, PageRequest.of(key, size));
```

spec을 사용하는건 매우 일반적이며 잘 활용하고 계십니다.
다만 join 을 이용하고 로직 순서를 조금씩 변경함으로써 코드를 좀 더 최적화할 수 있습니다 :)

2024-09-22 09:36 UTC, khj68 commented on src/main/java/com/potatocake/everymoment/service/DiaryService.java
> +        diaryRepository.deleteById(id);
실무에서는 데이터를 완전히 날려버리면 데이터 분석, 보안, 개인정보 등 문제가 생기는 경우가 있어 soft delete 를 적용하곤 합니다. 추가적인 정보로 알아두세요 :)

2024-09-22 09:36 UTC, khj68 commented on src/main/java/com/potatocake/everymoment/service/DiaryService.java
> +
jpa 변경 감지를 통해 diary 내에서 isBookmark만 수정하면 될 것 같습니다. 굳이 새로운 entity를 만들지 않아도 되겠습니다 :)

2024-09-22 09:36 UTC, khj68 commented on src/main/java/com/potatocake/everymoment/service/DiaryService.java
> +        Diary updatedDiary = Diary.builder()
jpa 변경 감지를 통해 diary 내에서 isPublic만 수정하면 될 것 같습니다. 굳이 새로운 entity를 만들지 않아도 되겠습니다 :)

2024-09-22 09:36 UTC, khj68 commented on src/test/java/com/potatocake/everymoment/EverymomentApplicationTests.java
> +
테스트 코드가 많이 부족하군요!

2024-09-22 09:36 UTC, khj68 commented on README.md
> +존재하지 않는 회원이라면 DB에 저장하고 JWT 발급하여 응답해주는 로직을 작성했는데 괜찮은 방식인지 궁금합니다!
네, 괜찮은 방식으로 보입니다.
다만 로그인/회원가입 시에 email, 이름 등 특정 정보만 받아오는 것으로 보이는데요.
카카오로부터 인증 받은 사용자인지를 어떻게 확정지을 수 있는지 고민이 필요해보입니다 :)
현재 상황으로는 악의적인 api 요청 시 카카오 인증 없이도 회원 가입이 진행될 것 같습니다.

2024-09-22 09:36 UTC, khj68 commented on README.md
> +또한 팀원분의 피드백을 받아 수정 예정이긴 하지만, category를 검색하는 부분도 함께 봐주시면 감사하겠습니다.
category 검색과 같은 부분은 join을 활용해도 좋을 것 같습니다.
서비스 레이어에서 specification은 자주 활용되고 있으니 걱정하지 않으셔도 좋습니다 :)

2024-09-22 09:36 UTC, khj68 commented on README.md
> +지금 방식이 조금 좋지 못하다는 생각이 드는데 어떻게 진행해야 할지 조언 부탁드립니다..!
master merge 시에만 ci/cd가 적용되는 것이 문제로 보입니다. 개발이나 베타 브랜치를 하나 둠으로써 그 쪽에서도 ci/cd를 돌리거나, weekly 에서도 배포를 제외한 파이프라인을 실행시킴으로써 ci/cd 문제를 master merge 전에 파악하는 것이 필요해보입니다 :)

2024-09-23 09:02 UTC, merged

2024-09-23 09:16 UTC, HyeJiJUN11 commented on src/main/java/com/potatocake/everymoment/service/DiaryService.java
> +                .locationPoint(diaryManualRequest.getLocationPoint().toString())
현재는 H2에 Point 자료형이 들어가지 않아 오류가 발생해, String으로 임시 처리 하고 있었습니다! DB연결 뒤에는 위경도 그대로 저장할 예정입니다.