feat: 내 일기 API 기능 구현
kakao-tech-campus-2nd-step3/Team21_BE pull request #8
Opened 2024-09-19 07:16 UTC by HyeJiJUN11

## 📝 작업 내용
- 자동/수동 일기 작성
- 일기 수정/삭제
- 내 일기 전체/상세 조회
- 내 일기 공개/북마크 설정

## 🔗 관련 이슈
close #6 
*이슈 번호랑 브랜치 명이 어긋나 있습니다.

2024-09-19 13:15 UTC, peeerr requested changes
코멘트 남긴 것들 반영 부탁드립니다
이해 안되는 부분들은 바로바로 얘기해 주세요!

2024-09-19 13:15 UTC, peeerr commented on src/main/java/com/potatocake/everymoment/service/DiaryService.java
> +        diaryRepository.save(updatedDiary);
이렇게 새로운 엔티티를 만들어서 save하면 기존 다이어리가 업데이트 되는 것이 아니라 새로운 엔티티가 생성되지 않나요?
업데이트가 잘 되더라도 아래 방식으로 바꾸는 것이 좋을 것 같습니다!

Diary 엔티티에 `updateXXX()` 메서드를 만들어서
`existingDiary.updateContent(content);` 이런식으로 사용하는 것을 추천드립니다.

이렇게 하고나서는 `diaryRepository.save(updatedDiary);`가 필요 없습니다

JPA Dirty Checking 검색해서 확인해 보는 것을 추천드립니다!

2024-09-19 13:15 UTC, peeerr commented on src/main/java/com/potatocake/everymoment/service/DiaryService.java
> +        diaryRepository.save(updatedDiary);
마찬가지로 Diary 엔티티내에 `switchBookmark()` 메서드를 두어 이를 호출하는 방식으로 업데이트하면 한 줄로 처리할 수 있습니다!

2024-09-19 13:15 UTC, peeerr commented on src/main/java/com/potatocake/everymoment/repository/DiaryCategoryRepository.java
> +@Repository
`@Repository` 어노테이션은 불필요해 보입니다!

2024-09-19 13:15 UTC, peeerr commented on src/main/java/com/potatocake/everymoment/dto/response/NotificationResponseDTO.java
> +}
항상 파일 마지막에는 빈 줄을 하나 삽입해 주세요!

![image](https://github.com/user-attachments/assets/25265d81-bafa-4937-a8aa-d79cf30050ab)
빈 줄이 없으면 깃허브에서 이렇게 보이게 됩니다.

![image](https://github.com/user-attachments/assets/8d78299a-cdd1-40d6-8dfd-7aa3dc2376d8)

이 설정을 체크하면 저장할 때마다 파일 마지막에 자동으로 빈 줄을 삽입해 줍니다!

2024-09-19 13:15 UTC, peeerr commented on src/main/java/com/potatocake/everymoment/dto/response/FileResponseDTO.java
> +@Builder
모든 DTO에 해당 어노테이션들을 달아 주셨는데 필요할 때만 사용 부탁드립니다!

2024-09-19 13:15 UTC, peeerr commented on src/main/java/com/potatocake/everymoment/controller/DiaryController.java
> +    public ResponseEntity<SuccessResponse<?>> createDiaryManual(
<?> 제네릭보다 명확한 타입을 지정 부탁드리겠습니다!

2024-09-19 16:05 UTC, HyeJiJUN11 commented on src/main/java/com/potatocake/everymoment/repository/DiaryCategoryRepository.java
> +@Repository
필요 없는 이유를 알 수 있을까요? 지금은 임의로 만들어놓은 레포지토리긴 하지만, 나중에 다이어리에 해당하는 카테고리를 저장하는 DB와 연결되는 것이어서요.

2024-09-19 16:09 UTC, HyeJiJUN11 commented on src/main/java/com/potatocake/everymoment/service/DiaryService.java
> +        //member id 가져옴
쿼리들을 모두 dto로 받아오라는 말씀이실까요?

2024-09-20 04:28 UTC, peeerr commented on src/main/java/com/potatocake/everymoment/service/DiaryService.java
> +        //member id 가져옴
저 많은 파라미터들을 dto에 담아서 하나의 파라미터(dto)만 받는게 좋을 것 같습니다

2024-09-20 04:34 UTC, peeerr commented on src/main/java/com/potatocake/everymoment/repository/DiaryCategoryRepository.java
> +@Repository
`JpaRepository` 인터페이스를 implements 하는 경우에는 해당 어노테이션 없이도 잘 동작합니다!
리파지토리 클래스라는걸 명시적으로 표현하고 싶다면 `@Repository`를 달아도 될 것 같은데 패키지명과 접미사로 충분히 나타내고 있기 때문에 불필요해 보입니다

2024-09-20 04:39 UTC, peeerr approved these changes

2024-09-20 05:04 UTC, merged